jenkins:
  systemMessage: "Jenkins configuré via Configuration as Code"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}

  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"

credentials:
  system:
    domainCredentials:
      - credentials:
          # GitLab Token
          - gitLabApiTokenImpl:
              scope: SYSTEM
              id: "gitlab-token"
              apiToken: ${GITLAB_API_TOKEN}
              description: "GitLab API Token"

          # Docker Hub
          - usernamePassword:
              scope: SYSTEM
              id: "docker-hub"
              username: ${DOCKER_USERNAME}
              password: ${DOCKER_PASSWORD}
              description: "Docker Hub Credentials"

tool:
  git:
    installations:
      - name: Default
        home: git

jobs:
  - script: >
      folder('applications') {
          description('Dossier contenant tous les pipelines des applications')
      }

unclassified:
  gitlabConnectionConfig:
    connections:
      - apiTokenId: "gitlab-token"
        name: "GitLab"
        url: "https://gitlab.com"