jenkins:
  systemMessage: "Jenkins minimal pour test CasC - LOGGING DEBUG"
  # securityRealm:
  #   local:
  #     allowsSignup: false
  #     enableCaptcha: false
  # La section 'users' est gérée manuellement après le premier démarrage, il faut rentrer le mot de passe de l'utilisateur admin qui est dans le fichier .env

  # authorizationStrategy:
  #   globalMatrix:
  #     permissions:
  #       - "Overall/Administer:${JENKINS_ADMIN_ID:-admin}"
  #       - "Overall/Read:authenticated"

# Nécessite les plugin "Support Core" et "script security" installé
# logging:
#   loggers:
#     hudson.plugins.git: FINER
#     org.jenkinsci.plugins.gitclient: FINER
#     org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition: FINER
#     com.cloudbees.plugins.credentials: FINER

# --- Configuration des logs via script Groovy intégré --- #
# jobs:
#   - file: /var/jenkins_config/jobs/airquality-pipeline.groovy

# Script Groovy pour définir les niveaux de log
security:
  scriptApproval:
    approvedSignatures:
      - "method java.util.logging.Logger setLevel java.util.logging.Level"

# --- Sections pour credentials --- #
credentials:
  system:
    domainCredentials:
      - credentials:
          # --- Credentials Standard Jenkins --- #
          # Token GitLab pour la connexion Jenkins et le scan des dépôts (en tant que GitLab API Token)
          # Décommenté car utilisé par le script Groovy gitlab-config.groovy
          - gitLabApiTokenImpl:
              scope: SYSTEM
              id: "gitlab-token"
              apiToken: ${GITLAB_API_TOKEN}
              description: "GitLab API Token (Standard Connection - via GitLab Token Type)"
          # Identifiants Docker Hub pour pousser/tirer les images dans Jenkins
          - usernamePassword:
              scope: SYSTEM
              id: "docker-hub"
              username: ${DOCKER_USERNAME}
              password: ${DOCKER_PASSWORD}
              description: "Docker Hub Credentials (Standard)"

          # --- Credentials Spécifiques au Pipeline AirQuality --- #
          # Token GitLab utilisé par le Jenkinsfile AirQuality (transformé en Username/Password)
          - usernamePassword:
              scope: GLOBAL
              id: "credentialGitlab"
              username: "oauth2"
              password: ${GITLAB_API_TOKEN} # Note: GITLAB_API_TOKEN est utilisé comme un mot de passe ici
              description: "GitLab Token (Username/Password pour checkout HTTPS - pour AirQuality Jenkinsfile)"
          # Identifiants Docker Hub utilisés par le Jenkinsfile AirQuality
          - usernamePassword:
              scope: GLOBAL # Ou SYSTEM
              id: "dockerhub_airquality" # Nom spécifique requis par le Jenkinsfile
              username: ${DOCKER_USERNAME} # Assurez-vous que c'est le bon username pour cet identifiant
              password: ${DOCKER_PASSWORD} # Correction: Utilisation de la variable d'environnement
              description: "Docker Hub Credentials (pour AirQuality Jenkinsfile)"
          # Identifiants BDD pour Ansible
          - usernamePassword:
              scope: GLOBAL
              id: "bdd_user1"
              username: ${BDD_USER1_USERNAME}
              password: ${BDD_USER1_PASSWORD}
              description: "BDD User 1 (pour AirQuality Ansible)"
          - usernamePassword:
              scope: GLOBAL
              id: "bdd_user2"
              username: ${BDD_USER2_USERNAME}
              password: ${BDD_USER2_PASSWORD}
              description: "BDD User 2 (pour AirQuality Ansible)"
          - usernamePassword:
              scope: GLOBAL
              id: "bdd_user3"
              username: ${BDD_USER3_USERNAME}
              password: ${BDD_USER3_PASSWORD}
              description: "BDD User 3 (pour AirQuality Ansible)"
          - usernamePassword:
              scope: GLOBAL
              id: "bdd_user4"
              username: ${BDD_USER4_USERNAME}
              password: ${BDD_USER4_PASSWORD}
              description: "BDD User 4 (pour AirQuality Ansible)"
          - usernamePassword:
              scope: GLOBAL
              id: "bdd_user_admin"
              username: ${BDD_USER_ADMIN_USERNAME}
              password: ${BDD_USER_ADMIN_PASSWORD}
              description: "BDD User Admin (pour AirQuality Ansible)"

          # --- Credentials GitHub pour l'hébergement --- #
          - usernamePassword:
              scope: GLOBAL
              id: "github-hebergement"
              username: ${GITHUB_USER}
              password: ${GITHUB_PASSWORD}
              description: "GitHub Credentials pour le dépôt d'hébergement"

# --- Section Tool au niveau racine --- #
tool:
  git:
    installations:
      - name: Default
        home: git

# --- Section Jobs au niveau racine --- #
jobs:
  - file: /var/jenkins_config/jobs/airquality-pipeline.groovy

# Section unclassified commentée pour éviter des erreurs potentielles
unclassified:
  gitLabConnectionConfig:
    connections:
      - name: "GitLab"
        url: "https://gitlab.com"
        apiTokenId: "gitlab-token"
        clientBuilderId: "autodetect"
        connectionTimeout: 10000
        readTimeout: 10000
        ignoreCertificateErrors: false

  # Configuration des webhooks GitHub
  githubConfiguration:
    endpoints:
      - apiUri: "https://api.github.com"
        credentialsId: "github-hebergement"
        manageHooks: true