stages:
  - infra

deploy_jenkins:
  stage: infra
  image: python:3.10
  before_script:
    - pip install ansible
    - apt-get update && apt-get install -y sshpass
  script:
    - ansible-playbook -i hebergement_serveur/ansible/inventories/hosts.yml playbooks/deploy_jenkins.yml --user user --private-key "ssh/airquality_server_key"
  only:
    changes:
      - ci-cd/docker-compose.jenkins.yml
      - playbooks/deploy_jenkins.yml
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
    # À définir dans les variables GitLab CI/CD
    SSH_PRIVATE_KEY: $SSH_PRIVATE_KEY