services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    restart: unless-stopped
    user: root
    env_file:
      - ../../.env
    environment:
      - TZ=Europe/Paris
      - CASC_JENKINS_CONFIG=/var/jenkins_config
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_USER:-admin}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD:-password}
      - GITLAB_API_TOKEN=${GITLAB_API_TOKEN:-not_set}
      - GITLAB_URL=https://gitlab.com
      - DOCKER_REGISTRY_URL=https://index.docker.io/v1/
      - DOCKER_CREDENTIALS_ID=docker-hub
      - DOCKER_USERNAME=${DOCKER_USERNAME:-not_set}
      - DOCKER_PASSWORD=${DOCKER_PASSWORD:-not_set}
      - JENKINS_OPTS=--httpListenAddress=0.0.0.0
      - JAVA_OPTS=-Djava.awt.headless=true -Dhudson.DNSMultiCast.disabled=true -Dhudson.udp=-1 -Djenkins.install.runSetupWizard=false
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./casc:/var/jenkins_config
    networks:
      - traefik-public
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.iaproject.fr`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.http.routers.jenkins.service=jenkins"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "jenkins_logs"
        env: "JENKINS_ADMIN_ID,TZ"
        tag: "{{.Name}}/{{.ID}}"

volumes:
  jenkins_data:
    external: true

networks:
  traefik-public:
    external: true