# =====================================================
# Fichier docker-compose pour Jenkins avec Docker et CasC
# - Déploie Jenkins avec accès au socket Docker
# - Monte la configuration CasC et les scripts d'init
# - Configure le reverse proxy Traefik
# =====================================================
services:
  jenkins:
    image: jenkins-with-docker:latest  # Image personnalisée avec Docker CLI et scripts d'init
    container_name: jenkins
    restart: unless-stopped
    user: "root"  # Nécessaire pour accéder au socket Docker
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - ../../.env
    environment:
      - TZ=Europe/Paris
      - CASC_JENKINS_CONFIG=/var/jenkins_config  # Chemin de la config CasC
      - JENKINS_ADMIN_ID=${JENKINS_ADMIN_USER:-admin}
      - JENKINS_ADMIN_PASSWORD=${JENKINS_ADMIN_PASSWORD:-password}
      - GITLAB_URL=https://gitlab.com
      - DOCKER_REGISTRY_URL=https://index.docker.io/v1/
      - DOCKER_CREDENTIALS_ID=docker-hub
      - JENKINS_OPTS=--httpListenAddress=0.0.0.0
      - JAVA_OPTS=-Djava.awt.headless=true -Dhudson.DNSMultiCast.disabled=true -Dhudson.udp=-1 -Djenkins.model.Jenkins.crumbIssuerProxyCompat=true
    volumes:
      - jenkins_data:/var/jenkins_home  # Données persistantes Jenkins
      - /var/run/docker.sock:/var/run/docker.sock  # Accès au démon Docker
      - ./casc:/var/jenkins_config  # Config CasC
      - ./casc/init.groovy.d:/var/jenkins_home/init.groovy.d  # Scripts Groovy d'init
      - ./plugins.txt:/usr/share/jenkins/ref/plugins.txt  # Liste des plugins
      - ../../ssh/airquality_server_key:/var/jenkins_secrets/airquality_server_key:ro  # Clé SSH
    networks:
      - traefik-public
    expose:
      - "8080"
    labels:
      # Labels Traefik pour le reverse proxy et la sécurité
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.jenkins.rule=Host(`jenkins.iaproject.fr`)"
      - "traefik.http.routers.jenkins.entrypoints=websecure"
      - "traefik.http.routers.jenkins.tls.certresolver=letsencrypt"
      - "traefik.http.services.jenkins.loadbalancer.server.port=8080"
      - "traefik.http.routers.jenkins.service=jenkins"
      - "traefik.http.services.jenkins.loadbalancer.passHostHeader=true"
      - "traefik.http.services.jenkins.loadbalancer.healthcheck.path=/login"
      - "traefik.http.services.jenkins.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.jenkins.loadbalancer.healthcheck.timeout=5s"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "jenkins_logs"
        env: "JENKINS_ADMIN_ID,TZ"
        tag: "{{.Name}}/{{.ID}}"

volumes:
  jenkins_data:

networks:
  traefik-public:
    external: true