# =============================================================================
# Inventaire Ansible
# =============================================================================
#
# Description:
#   Fichier d'inventaire Ansible définissant les hôtes et leurs variables pour
#   le déploiement des applications. Il inclut la configuration des serveurs,
#   des groupes d'applications et des variables globales.
#
# Structure:
#   - all: Variables globales pour tous les hôtes
#   - docker: Groupe des serveurs Docker
#   - applications: Groupe des applications avec leurs configurations spécifiques
#
# Variables globales:
#   - ansible_python_interpreter: Chemin de l'interpréteur Python
#   - ansible_user: Utilisateur pour la connexion SSH
#   - base_domain: Domaine principal pour toutes les applications
#   - docker_user: Utilisateur Docker Hub (depuis Vault en prod)
#   - working_dir: Répertoire de travail principal
#
# Groupes d'applications:
#   - airquality: Application de qualité de l'air
#   - prediction_vent: Service de prédiction du vent
#   - api_meteo: API météorologique
#
# Sécurité:
#   - Les secrets sont gérés via HashiCorp Vault en production
#   - Variables d'environnement en développement
# =============================================================================

---
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: user
    base_domain: iaproject.fr
    docker_user: "{{ lookup('env', 'DOCKER_USER') if env == 'dev' else lookup('community.hashi_vault.vault_read', 'secret/shared/docker/username') }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    working_dir: /hebergement_serveur

docker:
  hosts:
    server1:
      ansible_host: 192.168.1.134
      ansible_connection: local

  vars:
    traefik_network: traefik-public

# Variables spécifiques par application
applications:
  children:
    airquality:
      vars:
        app_domain: "airquality.{{ base_domain }}"
        app_port: 8092
        app_path: "{{ working_dir }}/applications/airquality"
    prediction_vent:
      vars:
        app_domain: "prediction-vent.{{ base_domain }}"
        app_port: 8093
        app_path: "{{ working_dir }}/applications/prediction-vent"
    api_meteo:
      vars:
        app_domain: "api-meteo.{{ base_domain }}"
        app_port: 8094
        app_path: "{{ working_dir }}/applications/api-meteo"