global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']

  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']

  - job_name: 'airquality'
    static_configs:
      - targets: ['airquality:3000']

  - job_name: 'extraction_cv'
    static_configs:
      - targets: ['extraction_cv:3000']

  - job_name: 'prevision_vent'
    static_configs:
      - targets: ['prevision_vent:3000']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']