---
- name: Configure OVH DNS records
  hosts: localhost
  gather_facts: false
  vars:
    ovh_endpoint: "ovh-eu"
    ovh_domain: "{{ lookup('env', 'OVH_DNS_ZONE') }}"
    server_ip: "{{ hostvars['server']['ansible_host'] }}"

  tasks:
    - name: Set up OVH DNS for main domain
      community.general.ovh_dns_record:
        state: present
        domain: "{{ ovh_domain }}"
        name: "airquality"
        type: A
        value: "{{ server_ip }}"
        endpoint: "{{ ovh_endpoint }}"

    - name: Set up OVH DNS for API subdomain
      community.general.ovh_dns_record:
        state: present
        domain: "{{ ovh_domain }}"
        name: "api.airquality"
        type: A
        value: "{{ server_ip }}"
        endpoint: "{{ ovh_endpoint }}"

    - name: Add CNAME record for www
      community.general.ovh_dns_record:
        state: present
        domain: "{{ ovh_domain }}"
        name: "www.airquality"
        type: CNAME
        value: "airquality.{{ ovh_domain }}."
        endpoint: "{{ ovh_endpoint }}"

    - name: Add CAA records for Let's Encrypt
      community.general.ovh_dns_record:
        state: present
        domain: "{{ ovh_domain }}"
        name: "airquality"
        type: CAA
        value: "0 issue \"letsencrypt.org\""
        endpoint: "{{ ovh_endpoint }}"