services:
  # Service d'initialisation
  init:
    image: alpine:latest
    volumes:
      - ./traefik-init.sh:/init.sh
      - ./entrypoint.sh:/entrypoint.sh
      - ./dynamic:/app/dynamic
      - ./acme.json:/app/acme.json
      - ../.env:/app/.env
    env_file:
      - ../.env
    environment:
      - TRAEFIK_USERNAME
      - TRAEFIK_PASSWORD
    working_dir: /app
    entrypoint: ["/entrypoint.sh"]
    # command: sh /entrypoint.sh
    # command: sh /init.sh
    # command: sh -c "chmod +x /init.sh && /init.sh"


  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    depends_on:
      - init
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "2222:22"  # Port 2222 externe vers 22 interne
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
      - ./acme.json:/letsencrypt/acme.json
      - ./dynamic:/etc/traefik/dynamic
    env_file:
      - ../.env
    environment:
      - TZ=Europe/Paris
      - OVH_ENDPOINT
      - OVH_APPLICATION_KEY
      - OVH_APPLICATION_SECRET
      - OVH_CONSUMER_KEY
      - OVH_DNS_ZONE
      - OVH_DNS_SUBDOMAIN
      - TRAEFIK_USERNAME
      - TRAEFIK_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.rule=Host(`traefik.iaproject.fr`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.middlewares=auth-basic@file"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"

networks:
  proxy:
    external: true