global:
  checkNewVersion: true
  sendAnonymousUsage: false

# Configuration des points d'entrée
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt
  ssh:
    address: ":2222"

# Configuration des certificats
certificatesResolvers:
  letsencrypt:
    acme:
      email: contact@iaproject.fr
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        entryPoint: web

# Configuration des providers
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# Configuration du dashboard
api:
  dashboard: true
  insecure: false

# Configuration des logs
log:
  level: DEBUG
  format: common